name: Test twill package using tox

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}
    - name: Install test runner
      run: pip install tox
    - name: Run twill tests
      run: tox -e py
    - name: Run software quality checks
      if: matrix.python == '3.13'
      run: TOXENV=ruff,mypy,docs,manifest tox
